### ISSUE TITLE
Volatile function recalculation inside a reference passed to non-volatile func doesn't trigger UDF recalculate

### ISSUE THREAD

**Issue by buybackoff** [Excel-DNA/ExcelDna#84] opened 2016-06-14 19:44 UTC
If I pass a range to my non-volatile UDF and set `allowReference = true`, and then inside that range I have a volatile function, e.g. RAND(), then my non-volatile UDF is not recalculated when RAND() is recalculated. If `allowReference = false`, then recalculation is triggered as expected. Is it a bug or feature? I want to avoid turning my UDFs into volatile functions, but I miss data updates with the current behavior.

**Comment by govert** [comment] 2016-06-14 20:09
If a function is marked as `IsMacroType=true` and has an argument that is marked `AllowReference=true` then the function is automatically considered volatile by Excel.

Can you elaborate what you mean by "I miss data updates with the current behaviour"? With a volatile function you should just have many unnecessary calculations.

Is there a particular reason why your function needs to be marked with `IsMacroType=true`? If not, removing that flag is the easy way to change the behaviour.

Otherwise you can explicitly reset the volatile flag inside the function, but you need to be sure that the function really does not depend on aspects of the sheet not explicitly passed in.

**Comment by buybackoff** [comment] 2016-06-14 20:19
My UDF is just not recalculating. I press F9, have a breakpoint inside my UDF, and clearly see that RAND() value inside an input range of my UDF changes, but my function is not recalculating even though some of its inputs changes. So obviously my UDF is not volatile, and I set it to be non-volatile both via the attribute and via a call to App.Volatile(false). Will post code later, now on phone.

**Comment by buybackoff** [comment] 2016-06-14 20:31
Just checked IsMacroType and it is true, but I indeed set it to non-volatile two times via the attribute and the call to App.Volatile. I do not remember why I set IsMacroType = true though, will try without it.

**Comment by buybackoff** [comment] 2016-06-14 20:40
Every time when its input values change. I repeat, RAND() is inside an
input range, not just somewhere on a sheet, but my UDF doesn't react to a
value change when allowReference is true.
On Jun 14, 2016 11:32 PM, "Govert van Drimmelen" <notifications@github.com>
wrote:

Do you want it to recalculate every time?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Excel-DNA/ExcelDna/issues/84#issuecomment-226007136>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAd5fETXmP-TNnW1u5eD-QsXrU-KykQJks5qLw_rgaJpZM4I1sBa>
.

**Comment by govert** [comment] 2016-06-14 21:11
Are you reading the contents of the ExcelReference inside your UDF?

If not, Excel might not be adding your function to the dependency tree in the way you expect.
Even if you are, you need to be careful with IsMacroType=true, as that lets you read uncalculated values.

Anyway, setting the IsVolatile=false in the attribute has no effect for such a function (IsMacroType=true with some AllowReference=true parameter).
Calling App.Volatile(false) woudl clear the volatile flag.

If you don't need IsMacroType=true, it's better not to set it.
In this case you can then remove App.Volatile(false) too.

Best is to make a small self-contained example that we can test and discuss further.

**Comment by govert** [comment] 2016-06-18 17:02
@buybackoff It seems to work better for making it non-volatile to call the C API `XlCall.Excel(XlCall.xlfVolaitle, false)` instead of the COM `Application.Volatile(false)` approach.

But I can't reproduce the issue you describe at all.

I use this function to test:
```c#
    static int counter = 1;
    [ExcelFunction]
    public static object TestRecalc([ExcelArgument(AllowReference = true)] object input)
    {
        return counter++;
    }
```

Can you describe how to reproduce the issues, or can I close?

**Comment by govert** [comment] 2016-06-18 17:11
This function works right:

```c#
    [ExcelFunction]
    public static object TestRecalc([ExcelArgument(AllowReference = true)] object input)
    {
        string result = "";
        if (input is ExcelReference)
        {

            var cells = ((ExcelReference)input).GetValue() as object[,];
            for (int i = 0; i < cells.GetLength(0); i++)
            {
                for (int j = 0; j < cells.GetLength(1); j++)
                {
                    result += cells[i, j].ToString();
                }
            }
        }
        return result;
    }
```

while this version has the problem (`IsMacroType=true`) and the volatile is switched off, so if doesn't recalculate:
```c#
    [ExcelFunction(IsMacroType =true)]
    public static object TestRecalc([ExcelArgument(AllowReference = true)] object input)
    {
        Excel(xlfVolatile, false);
        string result = "";
        if (input is ExcelReference)
        {

            var cells = ((ExcelReference)input).GetValue() as object[,];
            for (int i = 0; i < cells.GetLength(0); i++)
            {
                for (int j = 0; j < cells.GetLength(1); j++)
                {
                    result += cells[i, j].ToString();
                }
            }
        }
        return result;
    }
```

**Comment by buybackoff** [comment] 2016-06-19 11:48
@govert sorry, was going to post a repro on week-end (today). So you was able to reproduce it as indicated in the last comment with `IsMacroType =true`? With `IsMacroType =true` is this expected behavior?

**Comment by govert** [comment] 2016-06-19 12:39
I'm not sure about 'expected' behaviour. Clearly `IsMacroType=true` changes the calculation behaviour, so should be used very carefully. The same is true for interfering with the Volatile flag.

I've found that tour issue arises even without `AllowReference=true`.
Define this function:

```c#
    static int counter = 1;
    [ExcelFunction(IsMacroType =true)]
    public static object TestRecalc(object input)
    {
        Excel(xlfVolatile, false);
        return counter++;
    }
```

Then enter:
```
A1: =TestRecalc(A2)
A2: = RAND()
```
Now pressing `F9` will recalc cell A2, but not cell A1 (even though the input of `TestRecalc` has changed).

**Comment by govert** [comment] 2016-06-19 12:45
The same is true in VBA:
```vba
Function TestRecalcVBA(inputValue As Double)
    Static counter As Integer
    counter = counter + 1
    
    Application.Volatile False
    
    TestRecalcVBA = counter
End Function
```

does not recalculate when pressing F9.

**Comment by govert** [comment] 2016-06-19 12:49
And if you make the VBA input be a `Variant` (or give it no type), then it only calculates if you explicit read the value (without fiddling with Volatile).

So this does not recalc:
```vba
Function TestRecalcVBA(inputValue As Variant)
    Static counter As Integer
    counter = counter + 1
    TestRecalcVBA = counter
End Function
```

While this does:
```vba
Function TestRecalcVBA(inputValue As Variant)
    Static counter As Integer
    counter = counter + 1
    TestRecalcVBA = counter + inputValue
End Function
```

**Comment by buybackoff** [comment] 2016-06-19 16:29
With `AllowReference=false` and with processing the input I had the same function working properly. My conclusion is just to avoid using `IsMacroType=true`, not sure if that is an issue or a feature...

**Comment by govert** [comment] 2016-06-19 21:47
It's a quirk.

**Closed by govert** 2016-06-19 21:47 UTC
