### ISSUE TITLE
Registration [Error] Repeated function name: 'xxxxxx' - previous registration will be overwritten. 

### ISSUE THREAD

**Issue by ricardok1** [Excel-DNA/ExcelDna#116] opened 2017-02-28 22:10 UTC
Hi there

I've update ExcelDNA on my project and now I'm getting this error:

Registration [Error] Repeated function name: 'GetAmount' - previous registration will be overwritten. 

When I have many C# Overloading situations and all these are caught. Example:
`
public static decimal GetAmount(int      location, int account)

public static decimal GetAmount(string location, int account)
`

This is useful because is depending on the type invoked be a int or a string it should call different function.

Thanks for the wonderful library!
Ricardo

**Comment by ricardok1** [comment] 2017-02-28 22:50
My suggestion is to change this - please check if have any impact besides this class:

GetRegisterParameters:
   From: argumentNames += pi.Name;   
   To:     argumentNames += pi.Type.Name + ":" + pi.Name;

RegisterXlMethod:
  From:
      registrationInfo.Exists(ri => (
      (string)ri[3]).Equals((string)registerParameters[3], StringComparison.OrdinalIgnoreCase)
      )

   To:
      registrationInfo.Exists(ri => (
        (string)ri[3]).Equals((string)registerParameters[3], (...)) &&   // function name
        (string)ri[4]).Equals((string)registerParameters[4], (...))         //  argument name+type
     )

**Comment by govert** [comment] 2017-03-01 09:34
@ricardok1 The problem is not that the message is being shown at the wrong time. Excel does not support overloaded functions - you can't register a function name more than once (the last registration just 'wins'). So to implement this kind of overloading automatically, you'd need to take all the functions that share a name, and implement a single switching function that decides which overload to call based on the argument values passed from Excel. This single function then gets registered with Excel, with 'object' parameters.

**Comment by ricardok1** [comment] 2017-03-01 23:01
@govert I understand limited Excel perspective but on C# we can have it - how do suggest? 
I see that I was fooled by the cascade function on my class... always the last to be invoked and not the more efficient... :-)

**Comment by govert** [comment] 2017-06-18 21:35
Closing that as the behaviour is 'by design'.

**Closed by govert** 2017-06-18 21:35 UTC
