### ISSUE TITLE
Package build targets - check target build order

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#120] opened 2017-03-23 14:24 UTC
With the new package build approach, it seems that the two build targets "ExcelDnaBuild" and "ExcelDnaPack" (target "Build" depends on it) are running after the target "PostBuildEvent". I think this means the user can't copy or sign the packed add-in the post build event (since the Excel-DNA renamings and packing hasn't run yet).
This also means that updates of projects that depend on the post-build behaviour fails, and any errors in the post-build event blocks the Excel-DNA output files from being built, which can be inconvenient.

* Do we have control over the ordering of our custom build targets in the ExcelDna.AddIn.targets?
* Is there any guidance on the ordering of such custom build targets?
* Does it make sense to change this?

@caioproiete I'd be very interested in any light you might shed on this.

**Comment by govert** [comment] 2017-03-23 14:39
It might be as simple as:

* `<Target Name="ExcelDnaBuild" Condition="$(RunExcelDnaBuild)" BeforeTargets="PostBuildEvent">`

* `<Target Name="ExcelDnaPack" DependsOnTargets="ExcelDnaBuild" BeforeTargets="PostBuildEvent"  ...`

**Comment by govert** [comment] 2017-03-23 14:40
However, `BeforeTargets` is only available since MSBuild 4.0 - is this a constraint for us?

**Comment by caioproiete** [comment] 2017-03-23 19:07
@govert OK, I'll take a look at it later today.

I believe the issue is here:
https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/ExcelDna.AddIn.targets#L22

    <PropertyGroup>
      <BuildDependsOn>
        $(BuildDependsOn);
        ExcelDnaBuild;
        ExcelDnaPack;
      </BuildDependsOn>
    </PropertyGroup>

We're extending the build target via `BuildDependsOn`. If this target is run after the Post-Build events, we may be able to extend a different target that would work just as well (and that approach is compatible with previous versions of MSBuild).

`BeforeTargets` is also a viable solution. MSBuild 4.0 was introduced with Visual Studio 2010, so I'd say it is safe to require MSBuild 4.0, unless you want ExcelDna to support Visual Studio 2008 and/or older versions. What do you think?

**Comment by govert** [comment] 2017-03-23 19:11
@caioproiete Thank you for looking at this.

I don't think we have to support VS 2008.

**Comment by govert** [comment] 2017-04-17 20:33
@caioproiete  It seems like the PostBuildEvent story only works if there is a post-build event. Otherwise it now skips the entire ExcelDnaBuild step. I've changed to the BeforeTargets attribute approach to see it that's better.

**Comment by caioproiete** [comment] 2017-04-17 20:38
@govert Yes, I noticed that last week whilst reviewing PR #125 you've just merged.

I meant to give you a heads up to hold off merging that PR until I pushed my changes, but forgot and not it's too late.

No worries though. I already have a fix for that and a few more changes based on the PR #125. I'll push either later today or tomorrow night.

**Comment by govert** [comment] 2017-04-17 20:47
@caioproiete OK great - I'll wait for your stuff before I make another NuGet update.

**Comment by govert** [comment] 2017-04-28 09:31
@caioproiete I just want to check before I push new packages, whether any of the changes you wanted to add were serious, or were they mainly cosmetic?

**Comment by caioproiete** [comment] 2017-04-28 14:16
@govert Sorry, ended up being a busier week that I thought.

The changes are important. The Clean task is failing right now in couple scenarios (e.g. If a rebuild is called, before any build was ever called), and I've found the right event to extend in the MSBuild to run in the correct order.

I'll put some time aside this weekend to push this through.

**Comment by govert** [comment] 2017-04-28 15:00
@caioproiete OK great, thank you - I just wanted to check. I'll wait a bit for the release.

**Comment by caioproiete** [comment] 2017-05-07 23:17
@govert I've just opened a PR for the above. Sorry for the delay.

Re: MSBuild order, after reading the docs extending `CompileDependsOn` did the trick when compiling manually via Visual Studio but there seems to be optimizations when building via MSBuild and our tasks are not always being called (and therefore causing some tests to fail). Let's go with the `BeforeTargets` as per your comment.

After merging PR #130 you should be good to go for building a new NuGet package.

**Comment by govert** [comment] 2017-05-08 09:42
@caioproiete Wonderful - thank you very much!

**Closed** 2017-05-14 21:05 UTC
