### ISSUE TITLE
The custom functions with DNA runs more than once

### ISSUE THREAD

**Issue by limkinZero** [Excel-DNA/ExcelDna#65] opened 2016-03-10 11:36 UTC
I don't know why when I use a function with DNA from Excel, it's launch 2 o 3 times.

**Comment by govert** [comment] 2016-03-10 12:37
Async or RTD function?
It's normal for those.

IsMacroType=true with AllowReference=true parameters are also considered volatile by Excel.

Otherwise we need some more details or a simple reproduction.

On 10 Mar 2016, at 13:40, Pablo Vidal <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know why when I use a function with DNA from Excel, it's launch 2 o 3 times.

**Comment by limkinZero** [comment] 2016-03-10 13:30
I have declared as well:

 [ExcelFunction(Category = IPBConfig.CATEGORY, Name = "GET.TRADING.DATA", Description = "Get trading data info")]
        public static Object getTradingData([ExcelArgument(Description = "the first string")] String input)
        {
        ... [WEB SERVICE CLIENT]
        }

**Comment by govert** [comment] 2016-03-10 13:40
OK - does your function internally use some async mechanism based on Excel's RTD feature - perhaps ExcelAscynUtil.Run?

If so, there are some possible issues

* If called as an array function, there are many problems due to Excel's poor support for RTD inside array formulas:
   - the function will never properly complete or re-run
   - the function will be called be Excel once for the initial call, then once for the every cell in the array.

* If called as a single cell formula, the function will be called once when created, and once when the async call completes.

Does this match what you find?

________________________________

**Comment by govert** [comment] 2016-03-21 20:38
@limkinZero I'm planning to close this issue. Do you have any follow-up question, or more information about your situation?

**Closed** 2016-04-07 10:32 UTC
